package link.dwsy.ddl.XO.Enum.Article;

/**
 * @Author Dwsy
 * @Date 2022/10/16
 */


public enum CodeHighlightStyle {
    a11yDark,
    a11yLight,
    agate,
    anOldHope,
    androidstudio,
    arduinoLight,
    atomOneDarkReasonable,
    arta,
    ascetic,
    atomOneDark,
    atomOneLight,
    brownPaper,
    // brownPapersq.png,
    codepenEmbed,
    colorBrewer,
    dark,
    devibeans,
    Default,
    docco,
    far,
    foundation,
    felipec,
    githubDarkDimmed,
    github,
    githubDark,
    gml,
    gradientDark,
    gradientLight,
    googlecode,
    grayscale,
    hybrid,
    idea,
    intellijLight,
    irBlack,
    isblEditorDark,
    isblEditorLight,
    kimbieDark,
    kimbieLight,
    magula,
    lightfair,
    lioshi,
    monoBlue,
    monokaiSublime,
    monokai,
    nnfxDark,
    nightOwl,
    nnfxLight,
    nord,
    obsidian,
    pandaSyntaxDark,
    pandaSyntaxLight,
    paraisoDark,
    paraisoLight,
    pojoaque,
    // pojoaque.jpg,
    purebasic,
    qtcreatorDark,
    qtcreatorLight,
    rainbow,
    routeros,
    schoolBook,
    srcery,
    stackoverflowDark,
    shadesOfPurple,
    stackoverflowLight,
    sunburst,
    tokyoNightDark,
    tokyoNightLight,
    tomorrowNightBlue,
    tomorrowNightBright,
    vs,
    vs2015,
    xcode,
    xt256
}
